on: [push]

jobs:
  setup-without-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
      - run: kubeval --version

  setup-with-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          version: 0.15.0
      - run: kubeval --version

  test-env:
    runs-on: ubuntu-latest
    steps:
      - run: curl --version
      - run: ls -al /
      - run: ls -al /tmp/
      - uses: actions/checkout@v2
      - run: ls -al /
      - run: ls -al /tmp/
